name: Publish Packages

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  publish-linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Yarn
      run: yarn install
    - name: Build For Linux
      id: build-linux
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn build:bundle
        yarn release
  publish-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: Install Yarn
      run: yarn install
    - name: Build For Windows
      id: build-windows
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn build:bundle
        yarn release
  publish-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Yarn
      run: yarn install
    - name: Build For macOS
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn build:bundle
        yarn release
        
